apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/kubeStorage/nexus"
