apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-claim
  namespace: nexus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
