apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '443'
spec:
  selector: 
    app: jenkins
  type: NodePort  
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32002
    - name: https
      port: 443
      targetPort: 443
      nodePort: 32010