apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mariadb
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
          - containerPort: 3306
          volumeMounts:
          - mountPath: "/var/lib/mysql"
            subPath: "mysql"
            name: mariadb-volume
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
      volumes:
        - name: mariadb-volume
          persistentVolumeClaim:
            claimName: maria-claim
         