apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mariadb
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    nodePort: 32010
  clusterIP: None
  selector:
    app: mysql