apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/kubeStorage/mariadb"