apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-claim
  namespace: mariadb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
